export const TEAMS = [
    {id: "AFA", name: "Air Force"},
    {id: "AKR", name: "Akron"},
    {id: "BAMA", name: "Alabama"},
    {id: "APP", name: "Appalachian State"},
    {id: "ARIZ", name: "Arizona"},
    {id: "ASU", name: "Arizona State"},
    {id: "ARK", name: "Arkansas"},
    {id: "ARST", name: "Arkansas State"},
    {id: "ARMY", name: "Army"},
    {id: "AUB", name: "Auburn"},
    {id: "BALL", name: "Ball State"},
    {id: "BAY", name: "Baylor"},
    {id: "BSU", name: "Boise State"},
    {id: "BC", name: "Boston College"},
    {id: "BGSU", name: "Bowling Green"},
    {id: "BUFF", name: "Buffalo"},
    {id: "BYU", name: "BYU"},
    {id: "CAL", name: "California"},
    {id: "CMU", name: "Central Michigan"},
    {id: "CHAR", name: "Charlotte"},
    {id: "CIN", name: "Cincinnati"},
    {id: "CLEM", name: "Clemson"},
    {id: "CCAR", name: "Coastal Carolina"},
    {id: "COLO", name: "Colorado"},
    {id: "CSU", name: "Colorado State"},
    {id: "DEL", name: "Delaware"},
    {id: "DUKE", name: "Duke"},
    {id: "ECU", name: "East Carolina"},
    {id: "EMU", name: "Eastern Michigan"},
    {id: "FIU", name: "FIU"},
    {id: "FLA", name: "Florida"},
    {id: "FAU", name: "Florida Atlantic"},
    {id: "FSU", name: "Florida State"},
    {id: "FRES", name: "Fresno State"},
    {id: "UGA", name: "Georgia"},
    {id: "GASO", name: "Georgia Southern"},
    {id: "GSU", name: "Georgia State"},
    {id: "GT", name: "Georgia Tech"},
    {id: "HAW", name: "Hawaii"},
    {id: "HOU", name: "Houston"},
    {id: "ILL", name: "Illinois"},
    {id: "IND", name: "Indiana"},
    {id: "IOWA", name: "Iowa"},
    {id: "ISU", name: "Iowa State"},
    {id: "JVST", name: "Jacksonville State"},
    {id: "JMU", name: "James Madison"},
    {id: "KU", name: "Kansas"},
    {id: "KSU", name: "Kansas State"},
    {id: "KENN", name: "Kennesaw State"},
    {id: "KENT", name: "Kent State"},
    {id: "UK", name: "Kentucky"},
    {id: "LIB", name: "Liberty"},
    {id: "ULL", name: "Louisiana"},
    {id: "LT", name: "Louisiana Tech"},
    {id: "LOU", name: "Louisville"},
    {id: "LSU", name: "LSU"},
    {id: "MRSH", name: "Marshall"},
    {id: "UMD", name: "Maryland"},
    {id: "UMASS", name: "Massachusetts"},
    {id: "MEM", name: "Memphis"},
    {id: "MIA", name: "Miami"},
    {id: "M-OH", name: "Miami (OH)"},
    {id: "MICH", name: "Michigan"},
    {id: "MSU", name: "Michigan State"},
    {id: "MTSU", name: "Middle Tennessee"},
    {id: "MINN", name: "Minnesota"},
    {id: "MSST", name: "Mississippi State"},
    {id: "MIZZ", name: "Missouri"},
    {id: "MOST", name: "Missouri State"},
    {id: "NAVY", name: "Navy"},
    {id: "NCST", name: "NC State"},
    {id: "NEB", name: "Nebraska"},
    {id: "NEV", name: "Nevada"},
    {id: "UNM", name: "New Mexico"},
    {id: "NMSU", name: "New Mexico State"},
    {id: "UNC", name: "North Carolina"},
    {id: "UNT", name: "North Texas"},
    {id: "NIU", name: "Northern Illinois"},
    {id: "NW", name: "Northwestern"},
    {id: "ND", name: "Notre Dame"},
    {id: "OHIO", name: "Ohio"},
    {id: "OSU", name: "Ohio State"},
    {id: "OU", name: "Oklahoma"},
    {id: "OKST", name: "Oklahoma State"},
    {id: "ODU", name: "Old Dominion"},
    {id: "MISS", name: "Ole Miss"},
    {id: "ORE", name: "Oregon"},
    {id: "ORST", name: "Oregon State"},
    {id: "PSU", name: "Penn State"},
    {id: "PITT", name: "Pittsburgh"},
    {id: "PUR", name: "Purdue"},
    {id: "RICE", name: "Rice"},
    {id: "RUTG", name: "Rutgers"},
    {id: "SHSU", name: "Sam Houston"},
    {id: "SDSU", name: "San Diego State"},
    {id: "SJSU", name: "San Jose State"},
    {id: "SMU", name: "SMU"},
    {id: "USA", name: "South Alabama"},
    {id: "SCAR", name: "South Carolina"},
    {id: "USF", name: "South Florida"},
    {id: "USM", name: "Southern Miss"},
    {id: "STAN", name: "Stanford"},
    {id: "SYR", name: "Syracuse"},
    {id: "TCU", name: "TCU"},
    {id: "TEM", name: "Temple"},
    {id: "TENN", name: "Tennessee"},
    {id: "TEX", name: "Texas"},
    {id: "TAMU", name: "Texas A&M"},
    {id: "TXST", name: "Texas State"},
    {id: "TTU", name: "Texas Tech"},
    {id: "TOL", name: "Toledo"},
    {id: "TROY", name: "Troy"},
    {id: "TULN", name: "Tulane"},
    {id: "TLSA", name: "Tulsa"},
    {id: "UAB", name: "UAB"},
    {id: "UCF", name: "UCF"},
    {id: "UCLA", name: "UCLA"},
    {id: "CONN", name: "UConn"},
    {id: "ULM", name: "UL Monroe"},
    {id: "UNLV", name: "UNLV"},
    {id: "USC", name: "USC"},
    {id: "UTAH", name: "Utah"},
    {id: "USU", name: "Utah State"},
    {id: "UTEP", name: "UTEP"},
    {id: "UTSA", name: "UTSA"},
    {id: "VAN", name: "Vanderbilt"},
    {id: "UVA", name: "Virginia"},
    {id: "VT", name: "Virginia Tech"},
    {id: "WAKE", name: "Wake Forest"},
    {id: "WASH", name: "Washington"},
    {id: "WSU", name: "Washington State"},
    {id: "WVU", name: "West Virginia"},
    {id: "WKU", name: "Western Kentucky"},
    {id: "WMU", name: "Western Michigan"},
    {id: "WIS", name: "Wisconsin"},
    {id: "WYO", name: "Wyoming"},
    {id: "FCS", name: "FCS"},
];